name: swifty_companion
description: "The aim of the project is to build an application that will retrieve the information of 42 students, using the 42 API"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  get_it: ^7.6.4
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - config.env
    - assets/images/
